### PR TITLE
fix: remove JVM exit on SchedulingManager errors

### LINKED ISSUE #1645: Exiting the JVM in case of SchedulingManager failure is a little too extreme
In a scenario where one out of 2 DCs go down, Reaper will fail running Quorum queries that it needs for schedule management.
As such, if assertions are enabled, it will shut down entirely.

While that's manageable in a kubernetes environment where Reaper will get restarted automatically, it is a more challenging situation in non k8s environments.

We should probably make that an opt in feature rather than an opt out one and favor the stability of Reaper in such a case.

### PR DESCRIPTION
**Pull request by artsiom-bukhautsou**
Removes JVM exit on SchedulingManager errors

Fixes: #1645

### CODE REVIEW

File: src/server/src/main/java/io/cassandrareaper/service/SchedulingManager.java [hunk 1]
```diff
@@ -154,13 +154,8 @@ public void run() {
...
         }
-        try {
-          assert false : "if assertions are enabled then exit the jvm";
-        } catch (AssertionError ae) {
-          if (context.isRunning.get()) {
-            LOG.error("SchedulingManager failed. Exiting JVM.");
-            System.exit(1);
-          }
+        if (context.isRunning.get()) {
+          LOG.error("SchedulingManager encountered an error but will continue running.");
```
Comment (adejanovski) [inline src/server/src/main/java/io/cassandrareaper/service/SchedulingManager.java]: **todo:** I think we can fully remove this block. We already have exceptions logged above and this one doesn't really add anything useful for our users.

**Review by adejanovski — CHANGES_REQUESTED** [review]

File: src/server/src/main/java/io/cassandrareaper/service/SchedulingManager.java (hunk 1 above)
Comment (artsiom-bukhautsou) [reply src/server/src/main/java/io/cassandrareaper/service/SchedulingManager.java]: agree, fixed

**Review by adejanovski — APPROVED** [review]
