### PR TITLE
Filter out Stargate/coordinator nodes from calls to get live nodes or list tokens

### LINKED ISSUE #1432: Exceptions are being raised when using LOCAL mode with the mgmt-api
[Project board link](https://github.com/orgs/k8ssandra/projects/8/views/1?pane=issue&itemId=42255620)

When using Reaper in LOCAL dc Availability mode and the management api used for communications, exceptions are being raised and the app cannot work properly.
This is due to a wrong implementation of getUntranslatedHost() which returns the local endpoint whereas it should return the target connection host without any address translation.

### PR DESCRIPTION
**Pull request by adejanovski**
Fixes #1432

### CODE REVIEW

File: src/server/src/main/java/io/cassandrareaper/management/http/HttpCassandraManagementProxy.java [hunk 1]
```diff
@@ -405,7 +408,9 @@ public List<String> getLiveNodes() throws ReaperException {
       List<String> liveNodes = new ArrayList<>();
       EndpointStates endpoints = apiClient.getEndpointStates();
       for (Map<String, String> states : endpoints.getEntity()) {
-        if (states.containsKey("IS_ALIVE") && Boolean.parseBoolean(states.get("IS_ALIVE"))) {
+        if (states.containsKey("IS_ALIVE")
+            && Boolean.parseBoolean(states.get("IS_ALIVE"))
+            && !isCoordinatorNode(states)) {
```
Comment (emerkle826) [inline src/server/src/main/java/io/cassandrareaper/management/http/HttpCassandraManagementProxy.java]: suggestion:
I think it would be a small optimization to check if it's a coordinator node first as the states should almost always have an "IS_ALIVE" key. For coordinator-only nodes(i.e. Stargate), changing the order of the checks here will reduce the number of map reads I think.
```suggestion
        if (!isCoordinatorNode(states)
            && states.containsKey("IS_ALIVE")
            && Boolean.parseBoolean(states.get("IS_ALIVE"))) {
```

**Review by emerkle826 — APPROVED** [review]
small nit.

File: src/server/src/main/java/io/cassandrareaper/management/http/HttpCassandraManagementProxy.java (hunk 1 above)
Comment (adejanovski) [reply src/server/src/main/java/io/cassandrareaper/management/http/HttpCassandraManagementProxy.java]: addressed 👍
