### PR TITLE
Fix gossip state parsing for 4.0 rc1

### LINKED ISSUE #1086: New gossip state in 4.0 RC1 breaks Reaper cluster view
Gossip state has evolved in 4.0 and now contains a STATUS_WITH_PORT entry which seems to replace the STATUS one, although STATUS is still returned for the node from which the nodetool gossipinfo call ran: 

```
/172.31.23.61
  generation:1623140021
  heartbeat:10994
  LOAD:10991:291211.0
  SCHEMA:4782:29d2470d-d3a0-3ae7-942b-a76b0879320a
  DC:8:us-west-2
  RACK:10:us-west-2a
  RELEASE_VERSION:5:4.0
  NET_VERSION:1:12
  HOST_ID:2:3f4edba5-abc2-4144-bf40-23a2971d64b1
  RPC_READY:78:true
  NATIVE_ADDRESS_AND_PORT:3:172.31.23.61:9042
  STATUS_WITH_PORT:67:NORMAL,-1222353284784047876
  SSTABLE_VERSIONS:6:big-na
  TOKENS:66:<hidden>
/172.31.5.112
  generation:1623140021
  heartbeat:10998
  STATUS:68:NORMAL,-2615095451493062222
  LOAD:10996:293039.0
  SCHEMA:4805:29d2470d-d3a0-3ae7-942b-a76b0879320a
  DC:8:us-west-2
  RACK:10:us-west-2c
  RELEASE_VERSION:5:4.0
  RPC_ADDRESS:4:172.31.5.112
  NET_VERSION:1:12
  HOST_ID:2:ea1ed679-6d3c-440d-a5ee-99acbd73fe8f
  RPC_READY:78:true
  NATIVE_ADDRESS_AND_PORT:3:172.31.5.112:9042
  STATUS_WITH_PORT:67:NORMAL,-2615095451493062222
  SSTABLE_VERSIONS:6:big-na
  TOKENS:66:<hidden>
```

This makes Reaper believe all nodes but one are down: 
 !Reaper-4-rc1-cluster-view-issue.png|thumbnail! 

We need to push a fix that takes STATUS_WITH_PORT in priority and STATUS as fallback.

┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-553) by [Unito](https://www.unito.io)
┆Attachments: <a href="https://k8ssandra.atlassian.net/secure/attachment/10003/Reaper-4-rc1-cluster-view-issue.png">Reaper-4-rc1-cluster-view-issue.png</a>
┆Issue Number: K8SSAND-553
┆Priority: High

### PR DESCRIPTION
**Pull request by adejanovski**
fixes #1086 

4.0~rc1 introduced a new variable to replace STATUS named STATUS_WITH_PORT.
This PR takes it into account so that nodes can show up in the cluster view with the proper status.

### CODE REVIEW

File: src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java [hunk 1]
```diff
@@ -221,6 +227,89 @@ private void testParseEndpoint22StatusString(String sourceNode,
...
+            + "  STATUS:14:NORMAL,-3074457345618258603\n"
+            + "  LOAD:1231851:3988763.0\n"
+            + "  SCHEMA:10:2de0af6a-bf86-38e0-b62b-474ff6aefb51\n"
+            + "  DC:6:datacenter2\n"
+            + "  RACK:8:rack2\n"
+            + "  RELEASE_VERSION:4:3.0.8\n"
+            + "  RPC_ADDRESS:3:127.0.0.2\n"
+            + "  SEVERITY:1231899:0.0\n"
+            + "  NET_VERSION:1:10\n"
+            + "  STATUS_WITH_PORT:14:NORMAL,-3074457345618258603\n"
```
Comment (emerkle826) [inline src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java:262]: Did you intend to have `STATUS` and `STATUS_WITH_PORT` both in the status string here?

**Review by emerkle826 — APPROVED** [review]
:+1: 
Just a small comment on the test string for 4.0

File: src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java (hunk 1 above)
Comment (emerkle826) [reply src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java:262]: Is it guaranteed that the statuses would/should match? If not, I'm assuming STATUS_WITH_PORT wins, according to the ordering of the status matchers.

Comment (adejanovski) [reply src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java:262]: yep, so far I observed that they were strictly identical (which is expected I guess). This change comes from the fact that 4.0 allows to run several Cassandra instances on the same server. They're then identified by host:port instead of just host in 3.11.

Comment (emerkle826) [reply src/server/src/test/java/io/cassandrareaper/resources/view/NodesStatusTest.java:262]: :+1:
