### PR TITLE
Dropwizard auth

### LINKED ISSUE #1568: Expected class com.datastax.oss.driver.internal.core.ssl.JdkSslHandlerFactory
Hi, I am getting the below issue which using storage as Cassandra.
ERROR  [2025-05-23 09:54:02,925] [main] i.c.ReaperApplication - Storage is not ready yet, trying again to connect shortly... 
java.lang.IllegalArgumentException: Expected class com.datastax.oss.driver.internal.core.ssl.JdkSslHandlerFactory (specified by advanced.ssl-engine-factory.class) to be a subtype of com.datastax.oss.driver.api.core.ssl.SslEngineFactory
        at com.datastax.oss.driver.shaded.guava.common.base.Preconditions.checkArgument(Preconditions.java:458)

[cassandra-reaper-ssl.properties.txt](https://github.com/user-attachments/files/20408367/cassandra-reaper-ssl.properties.txt)
[cassandra-reaper.yaml.txt](https://github.com/user-attachments/files/20408366/cassandra-reaper.yaml.txt)

┆Issue is synchronized with this [Jira Story](https://datastax.jira.com/browse/REAP-218) by [Unito](https://www.unito.io)
┆Issue Number: REAP-218

### PR DESCRIPTION
**Pull request by adejanovski**
This pull request introduces significant updates to the authentication system in Cassandra Reaper, transitioning from Apache Shiro to Dropwizard Authentication with JWT support. It also includes updates to documentation and configuration files to reflect these changes, along with improvements to Docker configuration for easier deployment.
It also upgrades Dropwizard to v4 and the cassandra-all dependency to 5.0.3.

### Authentication System Updates:
* **Authentication Framework Transition**: Reaper now uses Dropwizard Authentication with JWT support, replacing Apache Shiro. This provides modern, stateless authentication suitable for both web UI and REST API access.
* **Configuration Enhancements**: Added detailed YAML configuration options for authentication, including JWT secret, session timeout, and user roles. Authentication is enabled by default but requires explicit user configuration.

### Documentation Updates:
* **Authentication Documentation**: Expanded the authentication section in `src/docs/content/docs/configuration/authentication.md` to include configuration details, user roles, and security considerations.
* **Docker Variables Documentation**: Added a new section in `src/docs/content/docs/configuration/docker_vars.md` to document environment variables for authentication configuration.

### Docker Configuration Improvements:
* **Environment Variables for Authentication**: Updated Docker documentation (`src/docs/content/docs/download/docker.md`) to include authentication-related environment variables (`REAPER_AUTH_USER`, `REAPER_AUTH_PASSWORD`, etc.) for secure deployments. [[1]](diffhunk://#diff-0efc068ad92e70321d4db2e6e4d54a5fc06e2ad2f0c4dc7c3630dd0d58e49bccR55-R65) [[2]](diffhunk://#diff-0efc068ad92e70321d4db2e6e4d54a5fc06e2ad2f0c4dc7c3630dd0d58e49bccR93-R94)
* **Simplified Docker Compose**: Removed the outdated `docker-compose.yml` file and associated services, simplifying the deployment process.

### Codebase Updates:
* **Dependency Migration**: Updated imports from `javax.ws.rs` to `jakarta.ws.rs` in `FORMATTING.md` to align with modern Java standards.

### CODE REVIEW

**Comment by adejanovski** [comment]
### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/adejanovski/pr-checks/d4b80fde-2c78-4ad3-bab3-d8903ee99310?refs=6c6b992fedee54cb6fedb2846da281ebe4b41d7b&source=prChecksComment)

:white_check_mark: **code/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/adejanovski/project/92329191-e09b-4a92-bcbd-6fdcb09d13ca/pr-check/6fa1fd81-8831-494a-abf8-a42384459ad7?refs=6c6b992fedee54cb6fedb2846da281ebe4b41d7b&source=prChecksComment)

File: src/server/src/main/java/io/cassandrareaper/ReaperApplication.java [hunk 1]
```diff
@@ -274,16 +280,85 @@ public void run(ReaperApplicationConfiguration config, Environment environment)
...
+              userConfig.getRoles());
+        }
+      } else {
+        LOG.info("ACCESS CONTROL: No users found in configuration");
+      }
+
+      String jwtSecret =
+          config.getAccessControl().getJwt() != null
+              ? config.getAccessControl().getJwt().getSecret()
+              : "MySecretKeyForJWTWhichMustBeLongEnoughForHS256Algorithm";
```
Comment (adejanovski) [inline src/server/src/main/java/io/cassandrareaper/ReaperApplication.java]: ### <sub></sub>&nbsp; Use of Hardcoded, Security-relevant Constants

Avoid hardcoding values that are meant to be secret. Found hardcoded `secret`.

<h6>
Line 315 | <a href="https://cwe.mitre.org/data/definitions/547.html">CWE-547</a> | <a href="https://docs.snyk.io/manage-risk/prioritize-issues-for-fixing/priority-score">Priority score 755</a></h6>
