### PR TITLE
Fix for NPE when a segment is aborted

### LINKED ISSUE #671: UI broken after a a repair is aborted (1.4.3)
**Spotted on 1.4.3 (9f07b65)**

webUI seems to be broken after an aborted repair.  After I have paused a repair and aborted it. 
The repairs list is not loading anymore. Also in the cluster view, the cluster on which the repair was running is not loading anymore.  Repairs are running properly and everything else seems to work. 

How to reproduce:
Start a repair run, pause it and abort it. 

Logs:
For repairs page:
```
ERROR  [2019-05-24 10:37:03,093] [dw-27 - GET /repair_run?clusterName=all] i.d.j.e.LoggingExceptionMapper - Error handling a request: ae52fed0abed819d 
java.lang.NullPointerException: null 
	at io.cassandrareaper.resources.view.RepairRunStatus.<init>(RepairRunStatus.java:175) 
	at io.cassandrareaper.resources.view.RepairRunStatus.<init>(RepairRunStatus.java:205) 
	at io.cassandrareaper.resources.RepairRunResource.getRunStatuses(RepairRunResource.java:708) 
	at io.cassandrareaper.resources.RepairRunResource.listRepairRuns(RepairRunResource.java:680) 
	at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) 
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) 
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) 
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) 
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) 
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) 
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) 
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) 
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) 
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) 
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) 
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45) 
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311) 
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) 
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) 
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) 
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) 
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) 
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) 
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) 
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) 
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) 
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) 
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239) 
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52) 
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724) 
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67) 
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) 
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 
	at org.eclipse.jetty.server.Server.handle(Server.java:531) 
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) 
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) 
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) 
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) 
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) 
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) 
	at java.lang.Thread.run(Thread.java:748) 
```

For cluster view: 
```
ERROR  [2019-05-24 10:38:03,931] [dw-26 - GET /cluster/foocass] i.d.j.e.LoggingExceptionMapper - Error handling a request: 0834817ecd1db63f 
java.lang.NullPointerException: null 
	at io.cassandrareaper.resources.view.RepairRunStatus.<init>(RepairRunStatus.java:175) 
	at io.cassandrareaper.resources.view.RepairRunStatus.<init>(RepairRunStatus.java:205) 
	at io.cassandrareaper.storage.CassandraStorage.getClusterRunStatuses(CassandraStorage.java:1180) 
	at io.cassandrareaper.resources.ClusterResource.getCluster(ClusterResource.java:133) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) 
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) 
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) 
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) 
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) 
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) 
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) 
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) 
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) 
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) 
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) 
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) 
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) 
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) 
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) 
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45) 
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311) 
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61) 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) 
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108) 
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) 
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) 
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) 
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) 
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) 
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) 
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) 
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) 
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) 
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) 
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) 
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) 
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) 
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219) 
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) 
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239) 
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52) 
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724) 
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67) 
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169) 
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) 
	at org.eclipse.jetty.server.Server.handle(Server.java:531) 
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) 
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) 
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) 
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) 
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) 
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) 
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762) 
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680) 
	at java.lang.Thread.run(Thread.java:748) 
```

### PR DESCRIPTION
**Pull request by adejanovski**
Fixes #671

We need to have a pause time on aborted runs so that we can compute the duration in the UI (uses the same code path as paused repairs).
Added tests for most combinations that are subject to preconditions.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Thanks for that @adejanovski !

Out of curiosity, why can't the UI use `endTime` for aborted repairs? That would make more sense. Or is that too difficult to change in the React code?

**Comment by adejanovski** [comment]
Fair enough @michaelsembwever, I updated the PR accordingly.
We'll now use `endTime` to compute the duration on aborted runs.

File: src/server/src/test/java/io/cassandrareaper/core/RepairRunTest.java [hunk 1]
```diff
@@ -0,0 +1,186 @@
+/*
+ * Copyright 2014-2017 Spotify AB
+ * Copyright 2016-2018 The Last Pickle Ltd
```
Comment (michaelsembwever) [inline src/server/src/test/java/io/cassandrareaper/core/RepairRunTest.java]:
```suggestion
 * Copyright 2019-2019 The Last Pickle Ltd
```

File: src/server/src/test/java/io/cassandrareaper/core/RepairRunTest.java [hunk 2]
```diff
@@ -0,0 +1,186 @@
+/*
+ * Copyright 2014-2017 Spotify AB
```
Comment (michaelsembwever) [inline src/server/src/test/java/io/cassandrareaper/core/RepairRunTest.java]:
```suggestion
 *
```

**Review by michaelsembwever — APPROVED** [review]
