### PR TITLE
issue 291  start time end time bug

### LINKED ISSUE #291: if endTime is set, so must startTime be set (v1.0.1)
I am unfortunately seeing issue similar to #281 even after upgrading to 1.0.1.

I am running one Reaper per DC and the `endTime is set, so must startTime be set` error is happening occasionally (I'd say less frequently than prior to upgrading to 1.0.1).

please see attached full log files from both DCs:
[logs.zip](https://github.com/thelastpickle/cassandra-reaper/files/1530109/logs.zip)

data causing the issue (you can see they come from dc2 log file):
```
cqlsh> select segment_start_time, segment_end_time from reaper_db.repair_run where id=231ee1e0-d871-11e7-8db9-7bb3e751dc82 and segment_id=23212c16-d871-11e7-8db9-7bb3e751dc82;

 segment_start_time | segment_end_time
--------------------+---------------------------------
               null | 2017-12-04 00:36:45.261000+0000

(1 rows)
```

everything goes back to normal when I fix the data manually by running:
```
update reaper_db.repair_run set segment_end_time=null where id=231ee1e0-d871-11e7-8db9-7bb3e751dc82 and segment_id=23212c16-d871-11e7-8db9-7bb3e751dc82;
```

### PR DESCRIPTION
**Pull request by michaelsembwever**
Fix #291 if endTime is set, so must startTime be set (v1.0.1) 

Commit d6e5a10 created the fault.
When the `updateRepairSegmentPrepStmt` statement was split into two, creating `insertRepairSegmentEndTimePrepStmt`,
it meant that calls to `SegmentRunner.postponse(..)` were no longer nulling endTime when resetting the RepairSegment to NOT_STARTED state.

The fix here is to

 - use `insertRepairSegmentEndTimePrepStmt` to null the endTime if state is NOT_STARTED (and live with tombstones created),
 - add method `RepairSegment.reset()` for the explicit purpose of resetting a segment to NOT_STARTED state with null startTime and endTime,
 - not permit nulls passed into `RepairSegment.Builder.startTime(..)`
 - add migration scripts (one more time) to fix any nulls in storage

### CODE REVIEW

File: src/server/src/main/java/io/cassandrareaper/storage/CassandraStorage.java [hunk 1]
```diff
@@ -630,14 +630,16 @@ assert hasLeadOnSegment(segment.getId())
             null != segment.getStartTime() ? segment.getStartTime().toDate() : null,
             segment.getFailCount()));
 
-    if (null != segment.getEndTime()) {
-      assert RepairSegment.State.DONE == segment.getState();
+    if (null != segment.getEndTime() || State.NOT_STARTED == segment.getState()) {
+      assert RepairSegment.State.RUNNING != segment.getState();
+      assert RepairSegment.State.NOT_STARTED != segment.getState() || null == segment.getEndTime();
+      assert RepairSegment.State.DONE != segment.getState() || null != segment.getEndTime();
```
Comment (adejanovski) [inline src/server/src/main/java/io/cassandrareaper/storage/CassandraStorage.java]: I find these tests hard to read because of the negations and the `||` operator. It's not obvious what is tested unless you give it a good thought.

Could we trade these against individual methods in the RepairSegment object ?
Something like : 
```
public boolean isNotStarted() {
  return RepairSegment.State.NOT_STARTED == getState();
}

public boolean isRunning() {
  return RepairSegment.State.RUNNING == getState();
}

public boolean isDone() {
  return RepairSegment.State.RUNNING != getState();
}


public boolean hasEndTime() {
  return null != getEndTime();
}
...
```
Then we would use those methods combined together in the assertions.
It wouldn't change much but the code intent would be easier to understand.

File: src/server/src/main/java/io/cassandrareaper/core/RepairSegment.java [hunk 2]
```diff
@@ -180,18 +190,20 @@ public Builder endTime(DateTime endTime) {
...
-      null != startTime || State.NOT_STARTED == state,
-      "startTime must be set if segment is RUNNING or DONE"); */
-
-      if (null != endTime && State.DONE != state) {
-        endTime = null;
-      }
-
-      if (startTime == null && endTime != null) {
-        startTime = endTime.minusSeconds(1);
+      if (STRICT) {
```
Comment (adejanovski) [inline src/server/src/main/java/io/cassandrareaper/core/RepairSegment.java:201]: I like the idea that the checks can be disabled.

File: src/server/src/main/java/io/cassandrareaper/core/RepairSegment.java [hunk 3]
```diff
@@ -103,6 +104,15 @@ public Builder with() {
     return new Builder(this);
   }
 
+  /** Reset to NOT_STARTED state, with nulled startTime and endTime. */
+  public Builder reset() {
```
Comment (adejanovski) [inline src/server/src/main/java/io/cassandrareaper/core/RepairSegment.java]: That's better than what I came up with. Nice !

**Review by adejanovski — APPROVED** [review]
Aside from minor possible code changes to make it easier to read, LGTM

File: src/server/src/main/java/io/cassandrareaper/storage/CassandraStorage.java (hunk 1 above)
Comment (michaelsembwever) [reply src/server/src/main/java/io/cassandrareaper/storage/CassandraStorage.java]: yeah fair point. i'll add those methods.
i'll also add assert messages, as this helps readability too…

Comment (michaelsembwever) [reply src/server/src/main/java/io/cassandrareaper/storage/CassandraStorage.java]: done. and changed the `assert` statements to `Preconditions.checkArgument(..)` as there's no performance overhead on these checks.

**Comment by michaelsembwever** [comment]
I'm happy with merging this. But will wait til I touch base with @adejanovski tonight.
